site_name: Leaddinfo – Lime CRM Documentation
nav:
  - Home: 'index.md'
  - Requirements: 'requirements.md'
  - How it works: 'howitworks.md'
  - Installation: 'installation.md'
  - Configuration: 'configuration.md'
  - Upgrading: 'upgrading.md'
  - Technical: 'technical.md'
  - Troubleshooting: 'troubleshooting.md'
theme:
  name: material
  palette:
    primary: 'teal'
    accent: 'teal'
  favicon: 'images/favicon.ico'
site_description: Leaddinfo – Lime CRM Documentation
site_author: Leadinfo
